### ISSUE TITLE
[WEB]-Selected branch is not displayed 

### ISSUE THREAD

**Issue by balajin958** [crawlinknetworks/rishta-crm#10]
**DESCRIPTION**:-Selected branch name is not displayed 

**STEPS**
"1)Click on retailer sales 
2)Click on order 
3)Click on filter
4)Click on select branch drop down 
5)Choose the branch & click on that branch name "

**OBSERVATION**
"Selected branch is not displayed

**Comment by srikanth340** [comment]
**Cause :**  Compare with function is not provided
**Solution** : Provided the compare with function
