### ISSUE TITLE
[WEB]-Mandatory fields accepting without data

### ISSUE THREAD

**Issue by balajin958** [crawlinknetworks/rishta-crm#101]
1)Upload distributor using excel sheet
2)Click on that created distributor in web
3)Click on edit option enter all fields except location
4)Click on save 
![DIS](https://user-images.githubusercontent.com/54259562/63744281-83abec00-c8bc-11e9-9169-0ca55205422e.png)

**Comment by srikanth340** [comment]
Made the location as not mandatory field.
