### ISSUE TITLE
[WEB]-User upload is accepting short form text for role

### ISSUE THREAD

**Issue by balajin958** [crawlinknetworks/rishta-crm#108]
1)Click on all user 
2)Click on upload 
3)Enter role name in short form 
![alluser](https://user-images.githubusercontent.com/54259562/63761467-d5656e00-c8de-11e9-8805-a65ba2ea3609.png)

**Comment by srikanth340** [comment]
**Cause :** It is take entered value as role instead of taking the existed one in the constants 
**Solution:** while uploading the user, role is taking the existed one by matching with entered value.
