### ISSUE TITLE
[Mobile]-Uploaded photo is not displayed in collect payment 

### ISSUE THREAD

**Issue by balajin958** [crawlinknetworks/rishta-crm#151]
1)Login to mobile
2)Click on retailer 
3)Click on retailer
4)Click on collect payment 
5)Click on take photo button & take photo
6)Cancel that photo & take photo again

OBSERVATION
Uploaded photo is not displayed

**Comment by Bharath-S1993** [comment]
Image visibility was gone so unable to display
