### ISSUE TITLE
[WEB]-Scroll bar is required for all modules

### ISSUE THREAD

**Issue by balajin958** [crawlinknetworks/rishta-crm#152]
1)Click on branch 
2)Click on all branch 
3)Click on column visibility 
4)Select all column 
5)Click on apply

Observation
Scroll bar is required 
![scroll bar 1](https://user-images.githubusercontent.com/54259562/64226843-9e0a4900-cefe-11e9-9796-a400cf2e0523.png)

**Comment by harshap2405** [comment]
Not an issue
