### ISSUE TITLE
[Mobile]-Alignment issue of login date & time for promoter 

### ISSUE THREAD

**Issue by balajin958** [crawlinknetworks/rishta-crm#167]
**STEPS**
1)Login as promoter 
2)Click on generate daily report 

**OBSERVATION**
Alignment issue of login date & time
![gener1](https://user-images.githubusercontent.com/54259562/64251516-5ef7ea00-cf36-11e9-9412-bf241b26901e.png)

**Comment by Bharath-S1993** [comment]
Resolved alignment issue
