### ISSUE TITLE
[WEB]-Routes & Sales Representative name should be interchanged  

### ISSUE THREAD

**Issue by balajin958** [crawlinknetworks/rishta-crm#193]
**STEPS**
1)Click on routes
2)Click on route planing
3)Select TSM

**OBSERVATION
!
![incorrect names1](https://user-images.githubusercontent.com/54259562/64527323-3e0f0a80-d323-11e9-8f3a-c04f54ae7a12.png)

**
In place Routes sales representative name is displayed & In place of Sales Repr Route name is displayed

**Comment by harshap2405** [comment]
fixed issue
