### ISSUE TITLE
[WEB]-In Location History Branch name is displayed wrong

### ISSUE THREAD

**Issue by balajin958** [crawlinknetworks/rishta-crm#194]
**STEP**S
1)Click on team
2)Click on location history 
3)Click on filter option

**OBSERVATION
![lh1](https://user-images.githubusercontent.com/54259562/64528520-503e7800-d326-11e9-9ed1-902e8a34e0ee.png)
**
Branch name is displayed wrong

**Comment by harshap2405** [comment]
issue fixed
