### ISSUE TITLE
[WEB]-pagination issue for distributor

### ISSUE THREAD

**Issue by balajin958** [crawlinknetworks/rishta-crm#195]
**STEPS**
1)Click on distributor
2)Click on all distributor
3)Select Branch 
4)Move to page 2
5)Click on choose branch 
6)Change the branch which has only one distributor

**OBSERVATION**
Distributor is displayed 
![pg11](https://user-images.githubusercontent.com/54259562/64531218-8f6fc780-d32c-11e9-9f90-4c169ea27cbd.png)

**Comment by harshap2405** [comment]
issue fixed
