### ISSUE TITLE
[WEB]-Executive is not found in advance filter for retailer

### ISSUE THREAD

**Issue by balajin958** [crawlinknetworks/rishta-crm#199]
**STEPS**
1)Click on retailer
2)Click on all retailer
3)Click on advance filter
4)Select Branch,SM,TSM & Executive
5)Click on apply
6)Now make none for SM
7)Click on SM & Select SM
8)Select TSM
9)Click on Executive

****OBSERVATION**
![exe1](https://user-images.githubusercontent.com/54259562/64611966-4ed98200-d3f0-11e9-950b-d05167239458.png)
**
No Executive found message is displayed

**Comment by harshap2405** [comment]
issue fixed
