### ISSUE TITLE
[WEB]-Product name is displayed BLANK

### ISSUE THREAD

**Issue by balajin958** [crawlinknetworks/rishta-crm#202]
**STEPS**
1)Click on product 
2)Click on SKU prices & Tax
3)Click on edit option
4)Click on product 
5)Change the product name
6)Click on Cancel

**OBSERVATION**
Product name is displayed blank 
![blank1](https://user-images.githubusercontent.com/54259562/64678744-d62e0080-d497-11e9-9a31-133c638dd948.png)

**Comment by harshap2405** [comment]
Issue not observed

**Comment by harshap2405** [comment]
not issue
