### ISSUE TITLE
[WEB]-All the order are not displayed 

### ISSUE THREAD

**Issue by balajin958** [crawlinknetworks/rishta-crm#205]
**STEPS**
1)Click on Retailer Sales
2)Click on order
3)Click on filter 
4)Select only branch 
5)Click on apply filter
6)Now update any one order

**OBSERVATION**
All the order is not displayed
![allnot1](https://user-images.githubusercontent.com/54259562/64761053-ca564300-d558-11e9-9e53-c2abbeb1b4ac.png)

**Comment by harshap2405** [comment]
fixed issue
