### ISSUE TITLE
[WEB]-User Count displayed wrong in filter

### ISSUE THREAD

**Issue by balajin958** [crawlinknetworks/rishta-crm#223]
**STEPS**
1)Click on all user 
2)Click on filter
3)Select Branch & Role only
4)Click on apply

**OBSERVATION**
User count is displayed wrong
![userfilter1](https://user-images.githubusercontent.com/54259562/65217371-8d96c880-dad1-11e9-86ea-d6544a4d11f3.png)

**Comment by harshap2405** [comment]
issue fixed
