### ISSUE TITLE
[WEB]-All the order is not displayed after filter

### ISSUE THREAD

**Issue by balajin958** [crawlinknetworks/rishta-crm#224]
**STEPS**
1)Click on Retailer Sales
2)Click on  order
3)Click on filter select only branch & click on apply
4)Now update any one order

**OBSERVED**
Remaining order is not displayed 
![orderiss1](https://user-images.githubusercontent.com/54259562/65245659-9ce63800-db0a-11e9-9a2e-358366e1a439.png)

**Comment by harshap2405** [comment]
issue fixed
