### ISSUE TITLE
[WEB]-Changed details is not saved in order

### ISSUE THREAD

**Issue by balajin958** [crawlinknetworks/rishta-crm#227]
**STEPS**
1)Click on order 
2)Click on create new order {select BRANCH,DISTRIBUTOR} 
3)Click on retailer{Note the Retailer}
4)Click on route {choose particular route of same branch}
5)Click on edit option & change the distributor
6)Click on create new order
7)Click on distributor{enter changed distributor name}
8)Click on retailer

**OBSERVATION**
Changed details is not saved

**Comment by harshap2405** [comment]
not an issue
