### ISSUE TITLE
[WEB]-Product is not displayed after filter in SKU price & Tax

### ISSUE THREAD

**Issue by balajin958** [crawlinknetworks/rishta-crm#244]
**STEPS**
1)Click on SKU price & Tax
3)Click on Filter 
4)Select Only Branch,Retailer Type & Chain Name

**OBSERVATION
![productfilter1](https://user-images.githubusercontent.com/54259562/65574796-01cae380-df8c-11e9-90e7-a984fe5397ae.png)
**
Product is not displayed

**Comment by harshap2405** [comment]
issue fixed
