### ISSUE TITLE
[WEB]-Created order is not displayed

### ISSUE THREAD

**Issue by balajin958** [crawlinknetworks/rishta-crm#245]
**STEPS**
1)Click on Retailer Sales
2)Click on order
3)Create order
4)In order list it is not displayed

**OBSERVATION
![ordernotd1](https://user-images.githubusercontent.com/54259562/65575602-d812bc00-df8d-11e9-83a1-f987a9e1d771.png)
**
Created order is not displayed, it is displayed only after filter

**Comment by harshap2405** [comment]
issue fixed
