### ISSUE TITLE
[WEB]- Unable to save RE-ORDER

### ISSUE THREAD

**Issue by balajin958** [crawlinknetworks/rishta-crm#249]
**STEPS**
1)Click on order 
2)Select any one order & cancel the order 
3)Click on re-order option for cancelled order
4)Tick mark the check box
5)Click on re-order

**OBSERVATION
![failed to save](https://user-images.githubusercontent.com/54259562/65758092-1054fe80-e136-11e9-8c11-efd23322cd32.png)
**
Unable to save,  failed to save pop-up message is displayed

**Comment by harshap2405** [comment]
issue fixed

**Comment by harshap2405** [comment]
issue fixed
