### ISSUE TITLE
[WEB]-Created Order is not displayed

### ISSUE THREAD

**Issue by balajin958** [crawlinknetworks/rishta-crm#250]
**STEPS**
1)Click on Retailer Sales
2)Click on Order
3)Click on Create New Order
4)Create Order

**OBSERVATION**
Created Order is not displayed
![crd03](https://user-images.githubusercontent.com/54259562/65936703-1bac7080-e43b-11e9-944e-b2d278f4a648.png)

**Comment by harshap2405** [comment]
Fixed
