### ISSUE TITLE
[WEB]-Branch name is not displayed in filter for all user

### ISSUE THREAD

**Issue by balajin958** [crawlinknetworks/rishta-crm#263]
**STEPS**
1)Login as **SM,TSM or EXECUTIVE**
2)Click on team
3)Click on all user 
4)Click on filter

**OBSERVATION
I**n filter of all user **BRANCH
![all filtrz](https://user-images.githubusercontent.com/54259562/66648812-1f65a180-ec4a-11e9-80c1-e6befa4d7a16.png)
** is not displayed

**Comment by harshap2405** [comment]
fixed
