### ISSUE TITLE
[WEB]-Product name & Branch is not displayed for view option

### ISSUE THREAD

**Issue by balajin958** [crawlinknetworks/rishta-crm#265]
**STEPS**
1)Login as SM or TSM
2)Click on Product
3)Click on SKU Prices & Tax
4)Click on Product name

**OBSERVATION**
Product name & Branch is not displayed for SM & TSM
![prdnamebrnan](https://user-images.githubusercontent.com/54259562/66736785-d13de180-ee87-11e9-9ee2-e9cb1798c35e.png)

**Comment by harshap2405** [comment]
not obserbed
