### ISSUE TITLE
[WEB]-Branch name is not displayed in filter order

### ISSUE THREAD

**Issue by balajin958** [crawlinknetworks/rishta-crm#266]
**STEPS**
1)Login as SM or TSM
2)Click on Retailer Sales
3)Click on Order
4)Click on Filter

**OBSERVATION**
Branch name is not displayed
![branchnambhjfgje](https://user-images.githubusercontent.com/54259562/66737072-9c7e5a00-ee88-11e9-829a-d2d75660f297.png)

**Comment by harshap2405** [comment]
fixed
