### ISSUE TITLE
[WEB]-In filter stock, filter order is displayed

### ISSUE THREAD

**Issue by balajin958** [crawlinknetworks/rishta-crm#268]
**STEPS**
1)Click on Retailer Sales
2)Click on stock
3)Click on filter

 **OBSERVATION**
Instead filter stock, filter order is displayed
![minorbugh](https://user-images.githubusercontent.com/54259562/66753602-d021aa00-eeb1-11e9-9662-8f46f7adb9ae.png)

**Comment by harshap2405** [comment]
fixed
