### ISSUE TITLE
Route name Ordering in Route Planning

### ISSUE THREAD

**Issue by Bikrantjena** [crawlinknetworks/rishta-crm#27]
Route Listing in Route Planning should be displayed in **Ascending** order of **Sales Rep** name and then by **RouteName**.
![WhatsApp Image 2019-08-19 at 5 00 26 PM](https://user-images.githubusercontent.com/54264856/63262353-53a08f80-c2a3-11e9-9e28-708236be8707.jpeg)

**Comment by Bikrantjena** [comment]
Save Button is not available in Route Planning.

**Comment by harshap2405** [comment]
> Save Button is not available in Route Planning.
Hello Sir,
It has auto save functionality sir,you just need to plot or unplot the blocks and the rest is handled back end side

**Comment by Bikrantjena** [comment]
OK..What about the first issue raised.

**Comment by harshap2405** [comment]
> OK..What about the first issue raised.

ya, sales rep is in first column and sorted in the ascending order
