### ISSUE TITLE
[WEB]-Page is displayed wrong for tour visit in web

### ISSUE THREAD

**Issue by balajin958** [crawlinknetworks/rishta-crm#270]
**STEPS**
1)Click on team
2)Click on tour visit

**OBSERVATION
![tourvispppp](https://user-images.githubusercontent.com/54259562/66995221-401b7480-f0ec-11e9-97af-5f27988110b9.png)
**
Instead of tour visit, create reatiler page is displayed

**Comment by harshap2405** [comment]
fixed
