### ISSUE TITLE
In WEB App, in VIEW User, more information about user device is required

### ISSUE THREAD

**Issue by Bikrantjena** [crawlinknetworks/rishta-crm#31]
After the App is implemented, for resolving the realtime issue of Field Force, We need to know his device details without asking him every time or remembering it. It will help in finding and informing users about, if old device models used for the App, which is not supporting. Details required are shown in Picture attached with this. 
![Capture](https://user-images.githubusercontent.com/54264856/63264233-34f0c780-c2a8-11e9-8271-94caff9675cd.PNG)

**Comment by srikanth340** [comment]
Provided the device details in user view.
![Screenshot from 2019-08-23 12-56-37](https://user-images.githubusercontent.com/54257793/63574487-813c5000-c5a5-11e9-913f-b1f3d1cda018.png)
