### ISSUE TITLE
Column visibility is not working properly

### ISSUE THREAD

**Issue by balajin958** [crawlinknetworks/rishta-crm#45]
**Description**:-Column visibility is not working properly

**STEPS**
"1)Click on branch 
 2)Click on all branch 
 3)Click on column visibility 
 4)Move last module name to first module
 5)Click on apply"

**OBSERVATION**
"After when we move to last module to first module it is not navigated

**Comment by srikanth340** [comment]
Not observed this issue Column visibility is not working properly in branch list.
