### ISSUE TITLE
"Search by phone text field is accepting wildcard  search"

### ISSUE THREAD

**Issue by balajin958** [crawlinknetworks/rishta-crm#46]
**Description**:-"Search by phone text field is accepting wildcard search"

**STEPS**
"1)Click on branch 
 2)Click on all branch 
 3)Click on search by phone number text field
 4)Enter only wild card search "

**OBSERVATION**
"After entering wild card search it is accepting

**Comment by srikanth340** [comment]
Implemented the new search functionality.
