### ISSUE TITLE
[Mobile] Invoice Pdf is not opening 

### ISSUE THREAD

**Issue by Ravslee** [crawlinknetworks/rishta-crm#50]

**Comment by Ravslee** [comment]
We found that, the third party app you are using for opening PDF has issue. 

Please make sure that you have the Adobe Acrobat Reader App installed in your device, Please use the below link to download the app.
[Click Here](https://play.google.com/store/apps/details?id=com.adobe.reader)

**Comment by paramanandapradhan** [comment]
Can you please verify and update
