### ISSUE TITLE
Retailer name is present two times

### ISSUE THREAD

**Issue by balajin958** [crawlinknetworks/rishta-crm#54]
**Description**:-Retailer name is present two times

**STEPS**
"1)Click on routes 
 2)Click on all routes
 3)Create route(Ex- Route 1)
 4)Click on all retailer
 5)Create retailer (Ex-Retailer 2)
 6)Create another route (Ex-Route 2)
 7)Now click on all retailer
 8)Click on retailer name(Retailer 2)
 9)Click on edit option & change to Route 2"

**OBSERVATION**
"After changing the route for retailer, retailer name is present for both the routes

**Comment by srikanth340** [comment]
**Cause :** Server side update retailer logic in wrongly implemented.
**Solution** :Corrected the logic in update retailer.
