### ISSUE TITLE
Route planning : Month mandatory field is not working

### ISSUE THREAD

**Issue by urmadhan** [crawlinknetworks/rishta-crm#60]
with out selecting month chart is displayed
![Screenshot (34)](https://user-images.githubusercontent.com/54258985/63507931-7bd3fc80-c4f6-11e9-8db1-eec8f06f5168.png)

**Comment by srikanth340** [comment]
**Cause :** List is not refreshing after select the month as none.
**Solution** : Refreshing the list when user select the month as none
