### ISSUE TITLE
[WEB]-Retailer is not displayed 

### ISSUE THREAD

**Issue by balajin958** [crawlinknetworks/rishta-crm#68]
Create Route & add retailer for created route, click on route name, retailer is not display

![Error](https://user-images.githubusercontent.com/54259562/63511831-df165c80-c4ff-11e9-9404-9937c7945eb4.png)

**Comment by srikanth340** [comment]
**Cause:** Null check is not provided.
**Solution :**  Null check provided in app-service for createUserActivity().
