### ISSUE TITLE
[WEB]-Sorting is not working

### ISSUE THREAD

**Issue by balajin958** [crawlinknetworks/rishta-crm#70]
**Description**:-Sorting is not working(For SM,TSM,Executive)

**STEPS**
1)Click on team
2)Click on all user 
3)Click on SM,TSM,Executive on column visibility column

**OBSERVATION**
Sorting is not working

**Comment by srikanth340** [comment]
**Cause :** While sorting correct sort filed is no sending to server.(always name is sending to server).
**Solution** : Sending the correct sort field to server and removed the sort field name in services.(name sort field is merging with params before sending the server).
