### ISSUE TITLE
Branch upload excel sheet : If you upload any other excel sheet, upload is successful and empty branch created

### ISSUE THREAD

**Issue by urmadhan** [crawlinknetworks/rishta-crm#72]
1. upload any other excel sheet  which is not related to branch or rishta , empty data Branch created 
2. upload empty excel sheet without entering any data in columns , error info message is not displayed.
3. mandatory fields are saved without data, If there is no data in mandatory fields, branch is created
4.  mobile number accepting CHARACTERS and more than 10 digits
5. issue in scroll bar.

[ABOVE ISSUES PRESENT IN ALL MODULES].

![Screenshot (39)](https://user-images.githubusercontent.com/54258985/63579294-e9902f00-c5af-11e9-8451-a699be31a335.png)

**Comment by urmadhan** [comment]
2nd and 4th not fixed

**Comment by balajin958** [comment]
Issue Need to Fixed
1)For We Can able  to Upload Distributor file 
2)For Delivery Vehicle we can able to upload Distributor,Route,Retailer,User File
3)For Product SKU we can able to Upload All File[For we can able to upload Branch,Distributor,Product Price,Retailer,Route,Vehicle & User]
