### ISSUE TITLE
[WEB]-Inactive product is displayed in report to while creating promoter

### ISSUE THREAD

**Issue by balajin958** [crawlinknetworks/rishta-crm#77]
Click on report to for promoter, after making inactive for product still is displayed for report in promoter
![Ristha-CRM-mobile-featurelist-1 pdf](https://user-images.githubusercontent.com/54259562/63588980-74c7ef80-c5c5-11e9-881e-27843bb1744b.png)

**Comment by srikanth340** [comment]
**Cause:** Fetching all products. (isActive :true is not sending to server).
**Solution** Fetching products based on isActive field.
