### ISSUE TITLE
While Creating retailer getting error 

### ISSUE THREAD

**Issue by balajin958** [crawlinknetworks/rishta-crm#89]
1)Alternative contact number accepting less than 10 digits 
2)While creating retailer user getting error, while creating user activity for that retailer 
message :Error on create ! ValidationError: activity.retailer: Cast to ObjectID failed for value "[Object: null prototype] " at path "activity.retailer""

**Comment by srikanth340** [comment]
1.Fixed the contact no accepting less than 10 digits
2.Fixed create retailer issue 
Cause: Retailer _id is missing in retailer object
Solution : By sending retailer object with _id
