### ISSUE TITLE
[WEB]-"All the retailers is not displayed & Retailers is  Displayed two times"

### ISSUE THREAD

**Issue by balajin958** [crawlinknetworks/rishta-crm#9]
**DESCRIPTION**:-"All the retailers is not displayed & Retailers is 
Displayed two times"

**STEPS**
"1)Click on retailer 
2)Click on all retailer 
3)Click retailer name 
4)Change Retailer type & chain name(Save it
5)Click on route name of particular retailer"

**OBSERVATION**
"All retailer is not displayed

**Comment by srikanth340** [comment]
**Cause :** In serve update retailer logic is wrongly implemented.
**Solution :** Corrected the update retailer logic.
