### ISSUE TITLE
[WEB]-Branch is not displayed while typing distributor name for retailer filter

### ISSUE THREAD

**Issue by balajin958** [crawlinknetworks/rishta-crm#92]
Branch name is not displayed while typing distributor name for retailer filter
![Retailer filter11](https://user-images.githubusercontent.com/54259562/63673321-b2b15780-c801-11e9-829f-6751075f8de1.png)

**Comment by srikanth340** [comment]
**Cause:** Same search object is used for all dropdown lists.
**Solution** : Provided different fields for  each dropdown list
